### PR TITLE
Issue #395 - Better Documentation.

### PR DESCRIPTION
**Pull request by Jam155**
This is the JavaDoc I've wrote so far detailing the public functions in two classes.

### CODE REVIEW

**Comment by edenman** [comment]
Sorry for the delay.  I don't think most of these comments are necessary.  The comment on makeCellView is good, I didn't realize how unintuitive that API might have been.  If you remove the second commit I'll merge this.  Oh and make sure you've signed the [CLA](https://docs.google.com/forms/d/e/1FAIpQLSeRVQ35-gq2vdSxD1kdh7CJwRdjmUA0EZ9gRXaWYoUeKPZEQQ/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1).

**Comment by Jam155** [comment]
@edenman So I've reverted this to the previous commit as specified. Hope that helps. I signed the CA when I originally created the Pull Request so I should be on there already.

**Comment by edenman** [comment]
Sorry, maybe I wasn't clear...I think you reverted the `makeCellView` commit, but that's the one I thought was the most useful.

**Comment by Jam155** [comment]
Ahh, okay. I'll sort that out.

**Comment by edenman** [comment]
Gonna close this, feel free to open a new one @Jam155

**Pull request closed without merging**
