### PR TITLE
allow_1_day_range

### PR DESCRIPTION
**Pull request by shanejmurphy**
* Modified some logic to allow users to select 1 day as a range as this may be useful in travel dates (for return etc)
* Added new attribute to allow for different drawables/colors for use with new rangeState
* Added some unit tests for testing same date selection and rangeState
* Updated sample app to display changes

### CODE REVIEW

**Comment by shanejmurphy** [comment]
I have created this PR as I feel a user should be able to select a range of 1 day as it can be useful in situations when you need to select a start and end date (so range mode is required when initialising the calendar.) In certain scenarios, the start and end date can be the same day.
I feel this PR addresses that issue.

**Comment by edenman** [comment]
Thanks for the PR, @shanejmurphy.  I don't think we'd want to do this without adding a new `SelectionMode` like `RANGE_ALLOWING_SINGLE_DAY` and a corresponding addition of a few tests to make sure the behavior is correct in both modes.  There are many existing projects that may not want to allow the range to start and end on the same day (hotel booking, for instance).

**Comment by shanejmurphy** [comment]
@edenman ,

Thanks for taking the time to review the PR and for your comments. 
I understand where you are coming from and your concerns about affecting projects that may not want to allow this behaviour. However, I would argue that the behaviour is not forced upon anyone, its just an extra option available to the user when RANGE mode is selected. 
For that reason, Im not sure creating a new SelectionMode makes a whole lot of sense as it would contain all the exact same logic with one or two extra date comparison checks. If the tests are robust enough it should be safe to add to SelectionMode.RANGE.
That being said, I have been testing the code over the last few days and found a small bug that needs fixing. However, Im not sure if this is a feature that you would be interested in adding? If so, I can add the fix to an updated PR, incorporating some of your suggestions.

**Comment by edenman** [comment]
@shanejmurphy my concern is that somebody is using `RANGE` in an app where they assume the current behavior (and maybe even crash if `range.start == range.end`) and I don't want to surprise them with crashes/weirdBehavior if they upgrade to latest.  Probably best to just close this for now, hopefully if anybody else needs this behavior they'll find this issue and can check out your fork.

**Pull request closed without merging**
