### PR TITLE
Remove 0 checks on dates, as 0 is a valid date

### PR DESCRIPTION
**Pull request by smaspe**

### CODE REVIEW

**Comment by smaspe** [comment]
apparently I forgot to update the tests. On it right now.

**Comment by smaspe** [comment]
I think the build failure is due to maven version. Using maven 3.2.5 gives me the same error (and also gives me the same error on master), using maven 3.1.1 works.

**Comment by edenman** [comment]
Yeah, travis builds are hosed.  I thought I had a test for the zero date stuff, strange that it's not failing.  Regardless, merging, I'll take a look at the tests now.

**Comment by edenman** [comment]
(nm, just noticed you removed the test.  carry on)

**Pull request merged**
