### PR TITLE
Update MonthView.java

### PR DESCRIPTION
**Pull request by JulianRayner**
Added locale support for day number display, RTL support is great, but for Arabic locale would like to see Arabic numbers

### CODE REVIEW

**Comment by edenman** [comment]
@JulianRayner this is great!  Can you please add a unit test for this in `CalendarPickerViewTest`?  

Also, we'll need you to sign our [CLA] (https://docs.google.com/a/squareup.com/forms/d/13WR8m5uZ2nAkJH41k7GdVBXAAbzDk00vxtEYjd6Imzg/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ) before I can merge this.

**Comment by JulianRayner** [comment]
Cool. Have signed. Will do unit test in a few days. Have a mega project on

On 1 December 2015 07:28:18 GMT+13:00, Eric Denman <notifications@github.com> wrote:
>@JulianRayner this is great!  Can you please add a unit test for this
>in `CalendarPickerViewTest`?  
>
>Also, we'll need you to sign our [CLA]
>(https://docs.google.com/a/squareup.com/forms/d/13WR8m5uZ2nAkJH41k7GdVBXAAbzDk00vxtEYjd6Imzg/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ)
>before I can merge this.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/square/android-times-square/pull/247#issuecomment-160715244

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edenman** [comment]
@JulianRayner would still love to merge this if you can add a test.  Or I'm happy to take it over if you're still slammed.

**Comment by edenman** [comment]
Taken over: #258.  Thanks for the contribution!

**Pull request closed without merging**
