### PR TITLE
Invoke OnDateSelectedListener#onDateUnselected() at clearOldSelections()

### PR DESCRIPTION
**Pull request by minsoopark**
Fix of @AAverin's issue #184.

### CODE REVIEW

**Comment by edenman** [comment]
LGTM.  @minsoopark can you sign our CLA? https://docs.google.com/forms/d/13WR8m5uZ2nAkJH41k7GdVBXAAbzDk00vxtEYjd6Imzg/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ

Also if you can squash your commits that would be great.  Let me know when both things are done and I'll merge.

**Comment by minsoopark** [comment]
@edenman Both things you said are done. Please check them!

**Comment by edenman** [comment]
Hrm, tt's showing 4 commits now.  Try doing a `git rebase -i 681aa67d3e1d15cf82602022d074036ff9764453` and marking your last three commits with `f` (for fixup, which removes the commit and ignores its commit message)

**Comment by minsoopark** [comment]
@edenman Now squashing is done. I'm sorry I'm late.

**Comment by edenman** [comment]
Thanks!

**Pull request merged**
