### PR TITLE
Update build tool 24.0.2 & Android gradle 2.2.0

### PR DESCRIPTION
**Pull request by niqo01**

### CODE REVIEW

**Comment by edenman** [comment]
@niqo01 can you try bumping the `build-tools-` version# in .travis.yml too?

**Comment by niqo01** [comment]
@edenman, well, the first error I got was that Android Gradle plugin 2.2.0 could no be found. I added `jcenter()` and now I am getting `You have not accepted the license agreements of the following SDK components:` I am not sure how to fix that one.

**Comment by JakeWharton** [comment]
It means you're not installing the dependencies that the project needs in
the .travis.yml

**Comment by edenman** [comment]
@niqo01 are you still working on getting this PR green?  the latest commit doesn't look like the rest of the commits

**Comment by niqo01** [comment]
@edenman ouch, I continued to work on my fork for custom features without realizing I was updating this PR too..
And no I am not working on fixing this change at the time being, sorry.

**Comment by edenman** [comment]
No worries :)

**Pull request closed without merging**
