### PR TITLE
Esperanto translation for invalid date

### PR DESCRIPTION
**Pull request by RobinvanderVliet**

### CODE REVIEW

**Comment by edenman** [comment]
Thanks @RobinvanderVliet (and sorry for the delay in noticing this PR)! I'll need you to sign the [Square CLA](https://docs.google.com/forms/d/13WR8m5uZ2nAkJH41k7GdVBXAAbzDk00vxtEYjd6Imzg/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ) before i can merge this.

**Comment by edenman** [comment]
@RobinvanderVliet bump

**Comment by RobinvanderVliet** [comment]
I signed the CLA.

**Comment by edenman** [comment]
@RobinvanderVliet thx again!

**Pull request merged**
