### PR TITLE
Modify .buildscript for gradle

### PR DESCRIPTION
**Pull request by skywave**
We missed modifying the buildscript for the Gradle migration in the last PR as per https://github.com/square/android-times-square/pull/230#issuecomment-133622694

### CODE REVIEW

**Comment by JakeWharton** [comment]
I will update the secrets.

**Comment by skywave** [comment]
You have an idea when to expect a gradle-built release/snapshot in the
repositories?

**Comment by edenman** [comment]
Just pushed 1.6.4 to maven central.  Thanks for the help, @skywave and @niqo01!

**Comment by JakeWharton** [comment]
New secrets are in. Snapshots will auto-deploy.

**Pull request merged**
