### PR TITLE
Day of week textAppearance

### PR DESCRIPTION
**Pull request by Shakezulla57**
Adding ability to define a text appearance style for the day of the week headers.

### CODE REVIEW

**Comment by edenman** [comment]
Wait, can't you just use `CalendarCell.DayHeader` for this?

**Comment by Shakezulla57** [comment]
It's possible I missed that, I'll have to take a look when I get back in the office.

**Comment by Shakezulla57** [comment]
Yes, indeed you can use the `CalendarCell.DayHeader` style. I saw how `app:tsquare_titleTextStyle` was implemented and just ran with that without thinking about overriding styles. Oops.

**Comment by edenman** [comment]
No worries!

**Pull request closed without merging**
